### ISSUE TITLE
[FEATURE REQUEST} - New Page for OBS Internal Sats

### ISSUE THREAD

**Issue by jmcc94** [lebaston100/mv-stats-for-obs#1]
Would it be possible to create another html source to be used to display internal OBS stats such as;

- fps
- render-total-frames
- render-missed-frames
- output-total-frames
- output-skipped-frames
- average-frame-time
- cpu-usage
- memory-usage

**Comment by lebaston100** [comment]
FPS is already available.
These pages are made to be very specific about most of the important stats.
At that point you could just window capture the obs stats panel.
I'll be closing this for now as it's not something i will add myself but would merge if someone made a PR for it. The project is in a stable state where updates are reserved for bugs and compatibility issues.
